export const DOMAIN_ERROR_CODES = [
    "INVALID_VERSION_TRANSITION",
    "START_GATE_FAILED",
    "CLOSE_GATE_FAILED",
    "INVALID_TODO_TRANSITION",
    "INVALID_UNDO_TRANSITION",
    "INVALID_DEFERRED_TRANSITION",
    "INVALID_CONSTRAINT_TRANSITION",
    "DEFERRED_ROUTE_CONTEXT_REQUIRED",
    "DEFERRED_ROUTE_TARGET_REQUIRED",
    "DEFERRED_ROUTE_TARGET_SELF",
    "DEFERRED_ROUTE_TARGET_UNKNOWN",
    "DEFERRED_ROUTE_TARGET_CROSS_PROJECT",
    "DEFERRED_ROUTE_TARGET_NOT_DOWNSTREAM",
    "INVALID_WORK_ITEM_ACTIVE",
    "INVALID_ASSET_PATH",
    "INVALID_OPERATION_ID",
    "CONTENT_LOCALE_REQUIRED",
    "CONTENT_LOCALE_MUST_BE_CONCRETE",
    "CONTENT_LOCALE_INVALID",
    "MISSING_REQUIRED_FIELD",
    "PROJECT_VERSION_MISMATCH"
];
export class DomainError extends Error {
    code;
    details;
    constructor(code, message, details) {
        super(message);
        this.name = "DomainError";
        this.code = code;
        this.details = details;
    }
}
